/*==============================
---------TB_MT_ORD_RSLT---------
===============================*/
CREATE OR REPLACE FORCE EDITIONABLE VIEW "EDU05"."VIEW_MT_ORD_RSLT" ("ORD_MT", "카테고리ID", "카테고리명", "상품ID", "상품명", "당월주문건수", "누적주문건수", "당월주문금액", "누적주문금액") AS 
  SELECT 
    ORD_MT
   ,CATEGORY_ID AS "카테고리ID"
   ,CATEGORY_NAME AS "카테고리명"
   ,PRODUCT_ID AS "상품ID"
   ,PRODUCT_NAME AS "상품명"
   ,QUANTITY AS "당월주문건수"
   ,SUM(QUANTITY) OVER(PARTITION BY CATEGORY_ID, PRODUCT_ID ORDER BY ORD_MT) AS "누적주문건수"
   ,ORD_AMT AS "당월주문금액"
   ,SUM(ORD_AMT) OVER(PARTITION BY CATEGORY_ID, PRODUCT_ID ORDER BY ORD_MT)  AS "누적주문금액"
FROM (
   SELECT 
       SUBSTR(O.ORDER_DATE_VC,1,6) AS ORD_MT
      ,C.CATEGORY_ID AS CATEGORY_ID
      ,C.CATEGORY_NAME AS CATEGORY_NAME
      ,P.PRODUCT_ID AS PRODUCT_ID
      ,P.PRODUCT_NAME AS PRODUCT_NAME
      ,SUM(F.QUANTITY) AS QUANTITY
      ,SUM(F.QUANTITY * F.UNIT_PRICE) AS ORD_AMT
   FROM ORDER_ITEMS F
   LEFT JOIN PRODUCTS P          ON F.PRODUCT_ID  = P.PRODUCT_ID 
   LEFT JOIN PRODUCT_CATEGORIES C  ON P.CATEGORY_ID = C.CATEGORY_ID 
   LEFT JOIN ORDERS   O          ON F.ORDER_ID    = O.ORDER_ID 
   --WHERE SUBSTR(O.ORDER_DATE_VC,1,6) LIKE '2024%'
   WHERE O.ORDER_DATE_VC LIKE '2024%'
   GROUP BY 
       SUBSTR(O.ORDER_DATE_VC,1,6) 
      ,C.CATEGORY_ID
      ,C.CATEGORY_NAME
      ,P.PRODUCT_ID
      ,P.PRODUCT_NAME
)
ORDER BY 1,2,4;